# Generated by Django 4.2.4 on 2023-08-08 20:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedRoom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('owner', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserved_room', to='rooms.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
