# Generated by Django 4.2.4 on 2023-08-16 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservedroom",
            name="booking_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservedroom",
            name="checking_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservedroom",
            name="checkout_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
