# Generated by Django 4.2.4 on 2023-08-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "booking",
            "0002_reservedroom_booking_date_reservedroom_checking_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservedroom",
            name="date",
        ),
        migrations.AlterField(
            model_name="reservedroom",
            name="booking_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reservedroom",
            name="checking_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservedroom",
            name="checkout_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
